name: Backend-CD
on:
  push:
    branches:
    - production
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16.0]
    
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
       node-version: ${{ matrix.node-version }}

    - name: Generate deployment package
      run: |
          cd ugram-backend
          yarn install
          yarn run build
          zip -r deploy.zip . -x '**node_modules**'
          mv deploy.zip ../
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Ugram-backend
        environment_name: Ugrambackend-env-1
        version_label: Deployment_Version_Dev${{github.SHA}}
        version_description: Deployment_Description_${{github.SHA}}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: deploy.zip
