
# This is a basic workflow to help you get started with Actions
name: Backend-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16.0]
    
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
       node-version: ${{ matrix.node-version }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    # CI=false is to let the build pass with warnings, will be remove later
    - name: App build
      run: |
          cd ugram-backend
          yarn install
          yarn run build
